---
.travis.yml:
  acceptance:
    - 'carbon_mono_instance'
    - 'carbon'
  forge_password: "MVrhernKquN/A78Pp1DRktryMadIUz86xVYQ6I8hvSfSyg/abi4QAUu116eKcz3T5xWS8GF+6prGHNTGnl58ST9rQ53ztzo5yg8rko1yGcEEaz/ftpVzt+ft5mQWo70WK3547L/C/c0iaji4/aAtZQS7jvnI4Onzb+naLSkrYDmh2jIl7mPDPIaLl8fo71MPXkVIgNniY1x1srhqzzQkWaeN73MEXrv9cW00sFpPmR0X+4cNuWzfDZdnuvbu8PbBF+j4JY62Dk9LxOgWL2sHQEANxTTxuHyWy4TDrK5B5tHhrHILbw8ZEbOjcfBjril/o6OOXHlm3Z8YA9hdELkMgwkTrqPgJ4BzpuIBUmVX25h3AkzmpEhaQXPp55uuDbxntZ2n7IlvBJED/MF4uu1mAFe/hSxrtetsi+oJIBzv/NYkbd4gg3723+x2e9UjVwIuddz1C4dK6oSwALf/c+42G0cAQD+wL1rx2epfGwtabyGUmqbP7kxwAdo6AeTFvlf4Q2JLB0GRrNm3RfNhH5WD1J4lbp8RPGfzExFZCWhK+izz360aGvqHG/5zCY63tJuMVv3X0eQPyv+SmRGCSZRSThhxBUncFG1ew/LZ//rPJmvo5xB/Xs9fl9fOPMR9c9xYXrvZSsarbMm4FNuxDBwju3C85bs9UmpgHSR/Zq0ozcw="
