---
language: ruby
sudo: false
cache: bundler
bundler_args: --without system_tests
script: ["bundle exec rake validate", "bundle exec rake lint", "bundle exec rake spec SPEC_OPTS='--format documentation'", "bundle exec rake metadata"]
matrix:
  fast_finish: true
  include:
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 3.0" FACTER_GEM_VERSION="~> 1.7.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
  - rvm: 2.1.0
    env: PUPPET_GEM_VERSION="~> 4.0"
  - env: BEAKER_set="debian-8-x86_64-openstack"
    bundler_args:
    script: '[ -z "${OS_AUTH_URL}" -o -z "${OS_USERNAME}" -o -z "${OS_PASSWORD}" -o -z "${OS_TENANT_NAME}" ] || bundle exec rspec spec/acceptance/carbon_mono_instance_spec.rb'
  - env: BEAKER_set="debian-8-x86_64-openstack"
    bundler_args:
    script: '[ -z "${OS_AUTH_URL}" -o -z "${OS_USERNAME}" -o -z "${OS_PASSWORD}" -o -z "${OS_TENANT_NAME}" ] || bundle exec rspec spec/acceptance/carbon_spec.rb'
  - env: BEAKER_set="centos-7-x86_64-openstack"
    bundler_args:
    script: '[ -z "${OS_AUTH_URL}" -o -z "${OS_USERNAME}" -o -z "${OS_PASSWORD}" -o -z "${OS_TENANT_NAME}" ] || bundle exec rspec spec/acceptance/carbon_mono_instance_spec.rb'
  - env: BEAKER_set="centos-7-x86_64-openstack"
    bundler_args:
    script: '[ -z "${OS_AUTH_URL}" -o -z "${OS_USERNAME}" -o -z "${OS_PASSWORD}" -o -z "${OS_TENANT_NAME}" ] || bundle exec rspec spec/acceptance/carbon_spec.rb'
notifications:
  email: false
deploy:
  provider: puppetforge
  user: camptocamp
  password:
    secure: "MVrhernKquN/A78Pp1DRktryMadIUz86xVYQ6I8hvSfSyg/abi4QAUu116eKcz3T5xWS8GF+6prGHNTGnl58ST9rQ53ztzo5yg8rko1yGcEEaz/ftpVzt+ft5mQWo70WK3547L/C/c0iaji4/aAtZQS7jvnI4Onzb+naLSkrYDmh2jIl7mPDPIaLl8fo71MPXkVIgNniY1x1srhqzzQkWaeN73MEXrv9cW00sFpPmR0X+4cNuWzfDZdnuvbu8PbBF+j4JY62Dk9LxOgWL2sHQEANxTTxuHyWy4TDrK5B5tHhrHILbw8ZEbOjcfBjril/o6OOXHlm3Z8YA9hdELkMgwkTrqPgJ4BzpuIBUmVX25h3AkzmpEhaQXPp55uuDbxntZ2n7IlvBJED/MF4uu1mAFe/hSxrtetsi+oJIBzv/NYkbd4gg3723+x2e9UjVwIuddz1C4dK6oSwALf/c+42G0cAQD+wL1rx2epfGwtabyGUmqbP7kxwAdo6AeTFvlf4Q2JLB0GRrNm3RfNhH5WD1J4lbp8RPGfzExFZCWhK+izz360aGvqHG/5zCY63tJuMVv3X0eQPyv+SmRGCSZRSThhxBUncFG1ew/LZ//rPJmvo5xB/Xs9fl9fOPMR9c9xYXrvZSsarbMm4FNuxDBwju3C85bs9UmpgHSR/Zq0ozcw="
  on:
    tags: true
    # all_branches is required to use tags
    all_branches: true
    # Only publish if our main Ruby target builds
    rvm: 1.9.3
