---
language: ruby
sudo: false
addons:
  apt:
    packages:
      - libaugeas-dev
    sources:
      - augeas
cache: bundler
bundler_args: --without system_tests
script: ["bundle exec rake validate", "bundle exec rake lint", "bundle exec rake spec SPEC_OPTS='--format documentation'"]
matrix:
  fast_finish: true
  include:
  - rvm: 2.1.9
    env: PUPPET_GEM_VERSION="~> 4.0"
  - rvm: 2.4.1
    env: PUPPET_GEM_VERSION="~> 5.0"
  - rvm: default
    sudo: required
    dist: trusty
    services: docker
    env: BEAKER_set="debian-8"
    bundler_args:
    script: sudo service docker restart ; sleep 10 && bundle exec rspec spec/acceptance/carbon_mono_instance_spec.rb
  - rvm: default
    sudo: required
    dist: trusty
    services: docker
    env: BEAKER_set="debian-8"
    bundler_args:
    script: sudo service docker restart ; sleep 10 && bundle exec rspec spec/acceptance/carbon_spec.rb
  - rvm: default
    sudo: required
    dist: trusty
    services: docker
    env: BEAKER_set="centos-7"
    bundler_args:
    script: sudo service docker restart ; sleep 10 && bundle exec rspec spec/acceptance/carbon_mono_instance_spec.rb
  - rvm: default
    sudo: required
    dist: trusty
    services: docker
    env: BEAKER_set="centos-7"
    bundler_args:
    script: sudo service docker restart ; sleep 10 && bundle exec rspec spec/acceptance/carbon_spec.rb
notifications:
  email: false
deploy:
  provider: puppetforge
  user: camptocamp
  password:
    secure: "MVrhernKquN/A78Pp1DRktryMadIUz86xVYQ6I8hvSfSyg/abi4QAUu116eKcz3T5xWS8GF+6prGHNTGnl58ST9rQ53ztzo5yg8rko1yGcEEaz/ftpVzt+ft5mQWo70WK3547L/C/c0iaji4/aAtZQS7jvnI4Onzb+naLSkrYDmh2jIl7mPDPIaLl8fo71MPXkVIgNniY1x1srhqzzQkWaeN73MEXrv9cW00sFpPmR0X+4cNuWzfDZdnuvbu8PbBF+j4JY62Dk9LxOgWL2sHQEANxTTxuHyWy4TDrK5B5tHhrHILbw8ZEbOjcfBjril/o6OOXHlm3Z8YA9hdELkMgwkTrqPgJ4BzpuIBUmVX25h3AkzmpEhaQXPp55uuDbxntZ2n7IlvBJED/MF4uu1mAFe/hSxrtetsi+oJIBzv/NYkbd4gg3723+x2e9UjVwIuddz1C4dK6oSwALf/c+42G0cAQD+wL1rx2epfGwtabyGUmqbP7kxwAdo6AeTFvlf4Q2JLB0GRrNm3RfNhH5WD1J4lbp8RPGfzExFZCWhK+izz360aGvqHG/5zCY63tJuMVv3X0eQPyv+SmRGCSZRSThhxBUncFG1ew/LZ//rPJmvo5xB/Xs9fl9fOPMR9c9xYXrvZSsarbMm4FNuxDBwju3C85bs9UmpgHSR/Zq0ozcw="
  on:
    tags: true
    # all_branches is required to use tags
    all_branches: true
    # Only publish if our main Ruby target builds
    rvm: 2.1.9
